### ISSUE TITLE
Bug: Log is flooded with RequestTimedOutErrors

### ISSUE THREAD

**Issue by winnieXY** [mblackstock/node-red-contrib-influxdb#143]
I just recognised that my log is flooded since a unkown time with a massive amount of errors (>200/s).

![grafik](https://github.com/mblackstock/node-red-contrib-influxdb/assets/6831918/d8a316a0-7c32-4593-bcd1-7697caa1a0a7)

I've already updated to the newest version 0.7.0 and increased the timeout from 10 -> 15 -> 20 -> 25. Nothing helps. 

The setup was running stable at least for three years before - so the write frequency should be okay (~ 1 msg/s roughly). 

I saw that there are already several bugs which are however closed. As I'm not sure which of them is the best one to track this down I've created this new one. Please feel free to reopen one of the others and close this one if this is more appropriate. 

If you need more information/  debug logs please let me know. I need to get back my debug console for testing as soon as possible :-)

**Comment by winnieXY** [comment]
After playing a little bit with node-red & influxdb I get now this (slightly different) error:
![grafik](https://github.com/mblackstock/node-red-contrib-influxdb/assets/6831918/5df0cdd8-46e1-4e5f-a41e-054977c0e436)

**Comment by Dufty-de** [comment]
Hi,
I have the same problem like winnieXY.
I´m also using V0.7.0
I'd triggered a couple of http requests with one inject node and want to transfer the result to influxdb. 
In order to strech the requests at the same time, i´ve mulitplied the injects and start each with a time shift of 0,2 s; but, the same result.
A restart of node red helps for a handfull of hours.
NodeRed and influxdb runing in a docker container on a synology with more than enough memory and are both up to date.
If you need more information feel free to contact me.

**Comment by winnieXY** [comment]
Any news on that? That's really a showstopper right now

**Comment by Bond246** [comment]
I think i don't have an solution.
But... Do you use influx 2 with flux-query oder with influx 1 and the older query language?

And do you use it in docker or as native installation?

**Comment by Dufty-de** [comment]
Hi,

 

I use a docker installation on a Synology with influx 2.75 and flux.

The problem is, the situation is not reproduceable: sometime it is and sometime not….

(at the moment not)

BR Wolfgang

 

Von: Florian ***@***.***> 
Gesendet: Freitag, 24. Mai 2024 09:35
An: mblackstock/node-red-contrib-influxdb ***@***.***>
Cc: Dufty-de ***@***.***>; Manual ***@***.***>
Betreff: Re: [mblackstock/node-red-contrib-influxdb] Bug: Log is flooded with RequestTimedOutErrors (Issue #143)

 

I think i don't have an solution.
But... Do you use influx 2 with flux-query oder with influx 1 and the older query language?

And do you use it in docker or as native installation?

**Comment by Dufty-de** [comment]
Hi,
yesterday i´ve had again the problem with the RequestTimedOutErrors.
My oberservation: 1st i´ve tried to transfer msg.payload as an array (i.e. msg.measurement = "power"; msg.payload =[{value: #}, {phase: "ph0"}, {level: "basement"}];
(you can transfer to influx not only the meassurement and the value, you can also add attributes to the measurement).
Here I´ve got the errors.
When I reduce the #of attributes to one, the node works without errors.
 (i.e. msg.measurement = "powerPhase0"; msg.payload =[{value: #}, {level: "basement"}];
or even a plain value in the payload and measurement="PowerPhase0Basement".
Maybe it´s a hint to solve the problem or to create a workaround
BR

**Comment by coolchip** [comment]
I've the same error. Using also Node-RED and InfluxDB as Docker container. 
It runs for years but now i get tons of errors.

The log of InfluxDB and another docker container showing also strange TCP connection errors. So I thought it might be a docker network error. But I have no idea how to inspect that.

**Comment by tinooo** [comment]
Same issue here. 
Using 0.7 on docker. influxdb 2.7.1, using flux.

I've can't nail down the issue. But I'm quite sure that even though the error is raised, the values are still being written to influxdb

**Comment by Bolukan** [comment]
Same experience and roaming internet for explanations: had node-red + influxdb both in docker for many years. average 1msg/s. Lot of time-outs, can't figure out why. Must have started with some influxdb version? Don't know.
I guessed the buffer for the calls loses calls so they are written but not ack.

**Comment by nordlings** [comment]
Did anyone confirm the closed issue #134 did not resolve this?

You should be able to pass connection timeout parameter in seconds to the node if you are on the lasted version pushed in late 2023.

**Comment by tinooo** [comment]
> Did anyone confirm the closed issue [#134](https://github.com/mblackstock/node-red-contrib-influxdb/issues/134) did not resolve this?
> 
> You should be able to pass connection timeout parameter in seconds to the node if you are on the lasted version pushed in late 2023.

yes, it does **NOT** resolve it. Issue is still present for me.

**Comment by ebabeshko** [comment]
I have the same situation. At some random periods node stops writing to InfluxDB, and error log is full of the following messages:
```
[error] [influxdb batch] RequestTimedOutError: Request timed out
WARN: Write to InfluxDB failed (attempt: 1). t [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (C:\node-red\node_modules@influxdata\influxdb-client\src\impl\node\NodeHttpTransport.ts:432:23)
    at ClientRequest.emit (node:events:519:28)
    at Socket.emitRequestTimeout (node:_http_client:931:9)
    at Object.onceWrapper (node:events:633:28)
    at Socket.emit (node:events:531:35)
    at Socket._onTimeout (node:net:605:8)
    at listOnTimeout (node:internal/timers:585:17)
    at processTimers (node:internal/timers:521:7)

```
and these ones:
```
[error] [influxdb batch] RequestTimedOutError: Request timed out
ERROR: Write to InfluxDB failed (attempt: 1). Error: Max retry time exceeded.
    at L.sendBatch (C:\node-red\node_modules@influxdata\influxdb-client\src\impl\WriteApiImpl.ts:164:23)
    at Timeout._onTimeout (C:\node-red\node_modules@influxdata\influxdb-client\src\impl\RetryBuffer.ts:134:16)
    at listOnTimeout (node:internal/timers:585:17)
    at processTimers (node:internal/timers:521:7)
```
No data is written into InfluxDB (I'm using 2.x version and Flux), although it is working without any errors reported in its log, and other clients, such as Telegraf, continue to read and write normally.

In my case, Node-RED with node-red-contrib-influxdb is running on one PC, while InfluxDB is running on another. Both PCs are on the same LAN running under Windows.

It looks like when there is some kind of connection problem, the node can't reconnect and enters an endless deadlock. The most frustrating thing is that it’s unpredictable when the node will fail next time - it could be after several hours or after couple of minutes.

Changing of request timeout setting doesn't help (tried 20-30-60-90s).

If I restart the flows or restart Node-RED, everything starts working smoothly again for an unpredictable period of time, and then the problem occurs again. Ugly workaround is to schedule regular node-red restarts, but of course, this is not a real solution.

node-red-contrib-influxdb requires version 1.33.2 of @influxdata/influxdb-client. Would it be worth trying the latest version (1.35)?

Any ideas how to troubleshoot this issue and resolve it?
